### ISSUE TITLE
AssistedInject Reflect

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/AssistedInject#132]
It would be great to have assisted inject working using reflection similar to dagger reflect.

Currently I'm not using this library because I just got rid of every single annotation processor in my debug builds and I'd like to keep it that way.

**Comment by JakeWharton** [comment]
This library has no means to provide a reflection-based equivalent since it generates code for any JSR330-compatible library to consume (whether they are reflection or annotation processor based). Any reflection-based implementation would have to be supported by the injection library itself for this to work.
