### ISSUE TITLE
@AssistedInject.Factory  limitation

### ISSUE THREAD

**Issue by MkhytarMkhoian** [square/AssistedInject#134]
Why you add this limitation "@AssistedInject.Factory must be declared as a nested type." ?

**Comment by JakeWharton** [comment]
What are you trying to do? The enclosing relationship currently simplifies some code generation tasks, but isn't _strictly_ required. Do you have a motivating use case?

**Comment by MkhytarMkhoian** [comment]
I'm thinking about writing codegen tool on top of the AssistedInject and one of the things I want us to generate default implementation of the AssistedInject.Factory

**Comment by 0neel** [comment]
@JakeWharton we have a case where moving a factory outside the class would be nice.

An assisted factory is used to create a presenter:
```kotlin
package some.feature

class SomePresenter @AssistedInject constructor(
    @Assisted override var view: SomeContract.View,
    ...
) : SomeContract.Presenter {

    ...

    @AssistedInject.Factory
    interface SomePresenterFactory {
        fun create(view: SomeContract.View): SomeContract.Presenter
    }
}
```

later the factory is used to create a presenter inside of a fragment:
```kotlin
import some.feature.SomePresenter.SomePresenterFactory

class SomeFragment @Inject constructor(
    presenterFactory: SomePresenterFactory
) : Fragment(...), SomeContract.View {

    private val presenter: SomeContract.Presenter by lazy {
        presenterFactory.create(this)
    }

    ...
}
```

So `SomeFragment` depends on an interface that is nested in `SomePresenter` which feels like a dependency on the implementation class which confuses people sometimes.
Not a big deal, just as said it would be nice to move the factory outside the class.

There is currently a way to make this but it requires having a bit of boilerplate:
```kotlin
interface SomePresenterFactory {
    fun create(view: SomeContract.View): SomeContract.Presenter
}

class SomePresenter @AssistedInject constructor(
    @Assisted override var view: SomeContract.View,
    ...
) : SomeContract.Presenter {

    ...

    @AssistedInject.Factory
    interface Factory : SomePresenterFactory
}
```

I understand that it can be hard to implement since the factory in our case returns not the class itself but its interface.

The only idea I currently have is to allow putting a factory interface inside of a base interface and generate a factory for every interface implementation, like this:
```kotlin
interface Presenter {
    ...

    @AssistedInject.Factory
    interface Factory {
        fun create(view: View): Presenter
    }
}
```
